language: node_js
node_js:
- 6
- 4
before_script:
- npm prune
script:
- npm run test
after_success:
- npm run ci:coveralls
before_deploy:
- npm run build
deploy:
  provider: npm
  on:
    repo: wikiwi/react-remove
    tags: true
    node: 4
  skip_cleanup: true
  email: vinh@wikiwi.io
